### ISSUE TITLE
BLAST mapping output

### ISSUE THREAD

**Issue by TlaskalV** [lmrodriguezr/enveomics#49]
Hello Luis,
this is not an issue but rather question about rec plots. Input into `BlastTab.catsbj.pl` are genome contigs and mapping file in BLAST format. How to get the BLAST form? Is it some kind of SAM/BAM/BED manipulation?

https://github.com/lmrodriguezr/enveomics/blob/ce5f3642cc6af9961b124d9c8850b04c0afca2ae/Scripts/BlastTab.catsbj.pl#L22

Thank you.

**Comment by lmrodriguezr** [comment]
Hello @TlaskalV 
This script was designed to use only BLAST-style output (e.g., from NCBI BLAST, MagicBlast, or BLAT). However, we've been working on a much friendlier (and way faster) version of the recruitment plots that does support SAM/BAM input:
https://github.com/KGerhardt/RecruitPlotEasy

I'd encourage you to use that instead, since it offers a much richer functionality, and directly supports the mapping format you have.
